# Generated by Django 3.0.4 on 2020-03-23 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Not specified', max_length=100)),
                ('salary', models.CharField(default='Best in Industry', max_length=100)),
                ('openings', models.IntegerField(default=1)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('views', models.IntegerField(null=True)),
                ('desc', models.TextField(default='No Description Available', null=True)),
                ('company_name', models.CharField(max_length=100)),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('eligibility', models.TextField(default='N.A.')),
                ('start_date', models.DateTimeField(null=True)),
                ('last_date', models.DateTimeField(null=True)),
                ('website', models.CharField(max_length=100, null=True)),
                ('post_type', models.IntegerField(choices=[(1, 'JOB'), (2, 'HACKATHON')], default=1)),
                ('company_logo_link', models.TextField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'APPROVE'), (2, 'KEEP AS DRAFT'), (3, 'REJECT')], default=2)),
            ],
        ),
    ]
