# Generated by Django 3.0.4 on 2020-03-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='author_email',
            field=models.CharField(default='N.A.', max_length=100),
        ),
        migrations.AlterField(
            model_name='employment',
            name='post_type',
            field=models.IntegerField(choices=[(1, 'JOB'), (2, 'INTERNSHIP')], default=1),
        ),
    ]
