# Generated by Django 3.0.4 on 2020-03-27 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200323_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='start_date',
        ),
    ]
