# Generated by Django 3.0.4 on 2020-03-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_employment_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='last_date',
            field=models.DateField(null=True),
        ),
    ]
