# Generated by Django 3.0.4 on 2020-04-04 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('organizer_logo_link', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'APPROVE'), (2, 'KEEP AS DRAFT'), (3, 'REJECT')], default=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='experience',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='organizer_logo_link',
        ),
        migrations.AddField(
            model_name='experience',
            name='organization',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='experience.Organizer'),
            preserve_default=False,
        ),
    ]
