# Generated by Django 3.0.4 on 2020-04-07 09:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_auto_20200404_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('user_about', models.TextField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='experience',
            name='author_about',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='author_email',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='author_name',
        ),
        migrations.AddField(
            model_name='organizer',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='experience',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='experience.Subscriber'),
            preserve_default=False,
        ),
    ]
